### ISSUE TITLE
Publish your list?

### ISSUE THREAD

**Issue by ehmkah** [synox/srf-radio-sync-to-spotify#1]
I like the idea especially its useful for other radiostations too, but at the moment I am not patient enough to figure out this refresh spotify stuff. :-(

Would you be so kind to share one example playlist for one day which you have created with srf-radio-sync-to-spotify?

**Comment by synox** [comment]
Hi Michael, see https://open.spotify.com/playlist/3kIk50muB3X5IUVHaMuCXq?si=_TAGFkReQZuAW0usXLM5lQ
I did run it once for 10 days. All my playlists are public. I did not try to run it automatically yet, as I did not listen through those yet.
